<!DOCTYPE html>
<html>
<!--Head
------------------------->
<head>
	<title>WebEdufinans</title>
	<!--Oderm dos Scripts é Extremamente importante-->
	<!--Jquery-->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="crossorigin="anonymous"></script>

	<!--Dtatables-->
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

	<!--FontWasone-->
	<script src="https://kit.fontawesome.com/a076d05399.js"></script>

	<!--Ajax-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 	crossorigin="anonymous"></script>



	<!--Bootstrap-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="	anonymous"></script>
 
	

	
	
	
	<!--Meus Arquivos-->
	<link rel="stylesheet" type="text/css" href="public/_css/estilo.css">
	<script src="public/_js/menu.js"></script>
	<script src="public/_js/home.js"></script>
</head>
<!--Body
------------------------->
<body>
	<!---Menu Superior-->
	<div class="menuSup">
		<!--Barra de Navegacao superior-->
		<nav class="navbar navbar-expand-md navbar-light p-0">
			
			<div id='abrirMenu' class="btn-Sup">
				
					<i class="fas fa-bars"></i>
				
			</div>
			<!-- Logo -->
			<a href="" class="navbar-brand">
				<h4 class="text text-success">WebEdufinans</h4>  
			</a>
	
			<div class="container">

				<div class="collapse navbar-collapse">

				

					<ul class="navbar-nav ml-auto ">
						<li class="nav-item">
							<a href="" class="nav-link text-success"> Eduardo </a>					
						</li>

						<li class="nav-item dropdown">
							<a href="" class="nav-link dropdown-toggle text-white" 
							data-toggle="dropdown">Configurações</a>
		  
							<div class="dropdown-menu">
								<a href="/WebEdufinans/sair" class="dropdown-item">Logout</a>
								<a href="/WebEdufinans/lotoFacil" class="dropdown-item">LotoFacil</a>
							  </div>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	
	</div>
	<div class="menuLateral">

		<ul>
			<li><a href="#"><i class="fas fa-qrcode">			</i></a></li>
			<li><a href="#"><i class="fas fa-link">				</i></a></li>
			<li><a href="#"><i class="fas fa-stream">			</i></a></li>
			<li><a href="#"><i class="fas fa-calendar-week">	</i></a></li>
			<li><a href="#"><i class="far fa-question-circle">	</i></a></li>
			<li><a href="#"><i class="fas fa-sliders-h">		</i></a></li>
			<li><a href="#"><i class="far fa-envelope">			</i></a></li>
		</ul>
	</div>

	<!--Secao
	---------------------------------------------------->
	  <section id='conteudoHome'>

   
        <?= $this->content() ?>
        
	  
	  		<!--Footer
    	 --------------------------------------------------->
    	 <footer class="mt-5 mb-4">
    	   <!--Container Footer-->
    	   <div class="container">
    	     <!--Linha Row-->
    	     <div class="row border-top">

    	   
    	       <div class="col-md-12 d-flex justify-content-center">
    	         <a href="" class="btn btn-outline-dark ml-2">
    	           <i class="fab fa-facebook"></i>
    	         </a>

    	          <a href="" class="btn btn-outline-dark ml-2">
    	           <i class="fab fa-youtube"></i>
    	         </a>

    	          <a href="" class="btn btn-outline-dark ml-2">
    	           <i class="fab fa-twitter"></i>
    	         </a>
    	          <a href="" class="btn btn-outline-dark ml-2">
    	           <i class="fab fa-instagram"></i>
    	         </a>
    	       </div>

    	       
    	     </div><!--Fim da Row Linha-->
    	   </div><!--Fim Cointainer-->   
      </footer>
    	

	</section>

	

</body>

</html>
