<script src="public/_js/cadastroDespesa.js"></script>
   <!-- Section MODAL
      ----------------------------------------------------------->  
        <!-- Modal -->
        <div class="modal fade" id="telaModal" tabindex="       -1" role="dialog" aria-labelledby="             exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <!--Container-->
                <div class="modal-content">
                    <header>
                        <div id="titulo_modal_div" class="modal-header      text-success">
                            <h5 class="modal-title" id="titulo_modal">TITULO MODAL</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </header>
                    <!--Seção Formulario nesses casos a Row vem depois do Formulario
                    ----------------------------------------------------------------------------------------->
                    
                        <div id="conteudo_modal" class="modal-body">

                            <!--Formulario
                             ----------------------------------------->
                            <form form action="" id="formReg" method="post">
   
                                <!--Linhas
                                  ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-2 control-label">Data:</label>

                                    <div class="col-sm-10 ">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-addon p-2">
                                                 <i class="fas fa-calendar-alt"></i>
                                            </div>
                                            <input class="form-control" type="date" value="2011-08-19" id="dData" name="dData" required >
                                        </div>
                                    </div>
                                </div>

                                <!--Linhas
                                  ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-2 control-label">Km:</label>

                                    <div class="col-sm-10 ">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append p-2">
                                                <i class="fas fa-biking"></i>
                                            </div>
                                            <input type="number" id="nKm" name="nKm" class="form-control" placeholder="KM" required>
                                        </div>
                                    </div>
                                </div>

                                 <!--Linhas
                                  ------------------->
                                  <div class="row form-group">

                                    <label class="col-sm-2 control-label">Titulo:</label>

                                    <div class="col-sm-10">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append  p-2">
                                                <i class="far fa-file"></i>
                                            </div>
                                            <input type="text" id="cTitulo" name="cTitulo" placeholder="Titulo" class="form-control" required>
                                        </div>
                                    </div>
                                </div>


                               <!--Linhas
                                  ------------------->
                                <div class="row form-group">

                                    <label class="col-sm-2 control-label">Produto:</label>

                                    <div class="col-sm-10">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append  p-2">
                                                <i class="far fa-file-code"></i>
                                            </div>
                                            <input type="text" id="cProduto" name="cProduto" placeholder="Produto" class="form-control" required>
                                        </div>
                                    </div>
                               </div>

                                <!--Linhas
                                 ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-2 control-label">Marca:</label>
                                
                                    <div class="col-sm-10">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append p-2">
                                                <i class="far fa-lightbulb"></i>
                                            </div>
                                            <input type="text" id="cMarca" name="cMarca" class="form-control" placeholder="Marca"  aria-required="true" >
                                        </div>
                                    </div>
                                </div>

                                <!--Linhas
                                 ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-2 control-label">Valor Unitario:</label>

                                    <div class="col-sm-10 mt-2">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append p-2">
                                            <i class="fab fa-cc-mastercard"></i>
                                            </div>
                                            <input type="number" id="nValorUni" value = '00,01' name="nValorUni" class="form-control" min=1 placeholder="00,01"  aria-required="true" >
                                        </div>
                                    </div>
                                </div>

                                <!--Linhas
                                ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-2 control-label">Quantidade: </label>

                                    <div class="col-sm-5 ml-1">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append p-2">
                                                <i class="fas fa-cubes"></i>
                                            </div>
                                            <input type="number" value='1' id="nQtd" name="nQtd" class="form-control" placeholder="1" min=1 max=20 "  aria-required="true" >
                                        </div>
                                    </div>
                                </div>
                                

                               <!--Linhas
                                ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-2 control-label">Valor Total:</label>

                                    <div class="col-sm-10 mt-2">
                                        <div class="input-group input-group-sm ">
                                            <div class="input-group-append p-2">
                                                <i class="fas fa-cart-plus"></i>
                                            </div>
                                            <input type="number" id="nValorTotal" name="nValorTotal" class="form-control" placeholder="00,00" disabled=""  aria-required="true" >
                                        </div>
                                    </div>
                                </div>

                                <!--Linhas
                                ------------------->
                                <div class="row form-group ">

                                    <label class="col-sm-12 control-label">Observação: 
                                        <i class="fas fa-book-open"></i>
                                    </label>

                                    <div class="col-sm-12 ">
                                        <div class="input-group input-group-sm ">
                                            <textarea class="form-control" id='cObs' name="cObs" rows="3"></textarea>
                                        </div>
                                    </div>
                                </div>


                                

                            </form>

                        </div>
          
                  

                    <div class="modal-footer">
      		        <button type="button" id="btn_registrar_modal" 		class="btn btn-secondary bg-success" 		data-dismiss="modal" >Registrar</button>
      		        <button type="button" id="btn_voltar_modal" 		class="btn btn-secondary bg-danger" 		data-dismiss="modal">Voltar</button>
					
      		      </div>

      		    </div>
      		</div>
        </div>
	

    